/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BarbeiroInfo.java
 *
 * Created on Jun 1, 2012, 12:59:24 PM
 */

package BarbeiroAdormecido;

/**
 *
 * Janela com texto explicativo sobre o problema do barbeiro adormecido
 */
public class BarbeiroInfo extends javax.swing.JFrame {

    /** Creates new form BarbeiroInfo */
    public BarbeiroInfo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setToolTipText("Há um 1 barbeiro e 1 cadeira de barbeiro, N cadeiras para os clientes esperarem.\nSe  não  há clientes  querendo  ser atendidos,      o  barbeiro  senta-se  e  dorme. \nQuando   um cliente  se aproxima  do  barbeiro dormindo,   o acorda e é atendido. \nSe chegarem mais clientes enquanto o barbeiro estiver ocupado cortando cabelo, \nsentam-se, caso tenham cadeiras livres, ou deixam a barbearia."); // NOI18N
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextPane1.setBackground(new java.awt.Color(224, 223, 227));
        jTextPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextPane1.setEditable(false);
        jTextPane1.setText("Há um 1 barbeiro e 1 cadeira de barbeiro, N cadeiras para os clientes esperarem.\nSe  não  há clientes  querendo  ser atendidos,      o  barbeiro  senta-se  e  dorme. \nQuando   um cliente  se aproxima  do  barbeiro dormindo,   o acorda e é atendido. \nSe chegarem mais clientes enquanto o barbeiro estiver ocupado cortando cabelo, \nsentam-se, caso tenham cadeiras livres, ou deixam a barbearia."); // NOI18N
        jTextPane1.setToolTipText(""); // NOI18N
        jTextPane1.setName("jTextPane1"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarbeiroInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
